### ISSUE TITLE
Remarks/advices 

### ISSUE THREAD

**Issue by Kinco-dev** [daobrussels/DAO_onchain#4]
Hello

@tsua0002 asked me as a friend to take a look at the contracts

I had a quick look at smart contracts and here is a non-exhaustive list of comments:

- `function contributeToProposal(uint256 proposalId) external payable onlyMembers`
=> A user can send funds to a proposal whose funds have already been collected.
=> No notion of proposal status (the status will help you manage the proposal and your frontend).
=> Can only vote "yes" for the proposal? Is this normal?

- `Proposal[] public proposals`
=> When you have several dozen proposals to display, and if you don't have any subgraphs, you run the risk of the call for proposals being too large, and you'll be unable to display your proposals. If you're planning to make your calls directly in the smart contract and display your data on a frontend, try to include optimized functions for this purpose.

- `return proposal.amount >= 1 ether && proposal.uniqueContributors >= 10 && proposal.voteCount >= 30;`
=> Why 1 ether? Why 10 unique contributors? Why 30 voteCount? This should be dynamic, depending on the proposal. (if you don't want it to be dynamic, it should at least be changeable by an admin via setters)

- `vote(uint256 proposalId) external onlyMembers {
        Member storage sender = members[msg.sender];
        require(!sender.hasVoted, "Already voted.");
        `
=> Be aware, it means a member can only vote once for his entire life
=> It should be possible to send funds in the same time than voting 

- `RewardDistributor`
=> For now, it is not very useful to deploy a separate smart contract just for it

- `function reviewContribution(uint256 contributionId) external onlyRegisteredMember`
=>Be aware, a member can vote to a contribution, and immediately review the contribution to make it validated

**⚠️⚠️⚠️ Exploit possible ⚠️⚠️⚠️**
```solidity
    function unlockFunds(uint256 proposalId) external onlyStewards {
        // Use canUnlockFunds to check if the conditions for unlocking funds are met.
        require(canUnlockFunds(proposalId), "Conditions to unlock funds not met.");
        Proposal storage proposal = proposals[proposalId];

        // Ensure the caller is the steward of the proposal.
        require(msg.sender == proposal.steward, "Only the steward of this proposal can unlock funds.");

        // Proceed with unlocking the funds.
        (bool sent,) = payable(proposal.steward).call{value: proposal.amount}("");
        require(sent, "Failed to send Ether");

        // Reset the proposal's amount to indicate that the funds have been disbursed.
        proposal.amount = 0;

        // Emit an event after the funds have been successfully transferred.
        emit FundsUnlocked(proposalId, proposal.steward, proposal.amount);
    }
```

   => A steward who is a contract can siphon all the ETH in the contract, even those not linked to his proposals. He can implement `receive() external payable {}` and loop on the `unlockFunds` function. Because `proposal.amount = 0` is called after the funds have been sent!

✅Solution:
```solidity
    function unlockFunds(uint256 proposalId) external onlyStewards {
        // Use canUnlockFunds to check if the conditions for unlocking funds are met.
        require(canUnlockFunds(proposalId), "Conditions to unlock funds not met.");
        Proposal storage proposal = proposals[proposalId];

        // Ensure the caller is the steward of the proposal.
        require(msg.sender == proposal.steward, "Only the steward of this proposal can unlock funds.");
        
        // Reset the proposal's amount to indicate that the funds have been disbursed.
        uint256 amountToSend = proposal.amount 
        proposal.amount = 0;

        // Proceed with unlocking the funds.
        (bool sent,) = payable(proposal.steward).call{value: amountToSend}("");
        require(sent, "Failed to send Ether");

        // Emit an event after the funds have been successfully transferred.
        emit FundsUnlocked(proposalId, proposal.steward, amountToSend );
    }
```

**Comment by arkano1dev** [comment]
Hi Kinco,

Thank you for your review of the BrusselsDAO contract. Here are the changes made to address the issues you raised:

#### Proposal Status Management

- Implemented ```ProposalStatus``` to prevent contributions to closed or funded proposals.
- Added ```openProposal``` and ```closeProposal``` functions for better status management.

#### Voting Mechanism
 
 - Enhanced the voting system to allow members to vote "yes" or "no" on proposals.

#### Dynamic Proposal Requirements

- Made the requirements for unlocking funds dynamic and configurable by the admin using ```setDefaultRequirements```.

#### Security in unlockFunds

- Improved the function with your proposed solution to prevent potential exploits.

I know there are still some modifications to be made, and I will take them into account. This contract is creating a DAO, and to be a true DAO, it is generated by the community. That's why the process is slow, and many functions are not yet 100% implemented. I consider myself just a translator of what the community demands to create this contract.

I will have more updates soon as I will be testing everything for a pilot with our Crypto Kastaar Beer project, where we will use the RewardDistributor contract to distribute shares of the business. I send you my regards and look forward to reading your feedback. Thank you very much for the time invested; your contribution is highly valuable.
